### PR TITLE
Support GHC-8.6.1

### PR DESCRIPTION
**Pull request by vrom911**

### CODE REVIEW

**Comment by christiaanb** [comment]
Thanks!

**Comment by vrom911** [comment]
@christiaanb, I wonder, would it be possible to make a revision on Hackage to update the `ghc` version upper bound in the dependencies (as the code was not changed)?

**Comment by christiaanb** [comment]
Done: http://hackage.haskell.org/package/ghc-tcplugins-extra-0.3/ghc-tcplugins-extra.cabal

**Comment by vrom911** [comment]
Thank you very much! 🙂

**Pull request merged**
