### PR TITLE
Prefer cabal conditionals over CPP heavy code.

### PR DESCRIPTION
**Pull request by philderbeast**
I don't normally make pull requests like this so I wrote a [blog post](https://blockscope.com/posts/2021-12-13-iffy-diffy.html) on why I prefer cabal conditionals over CPP heavy code.

I practised these techniques on `ghc-tcplugins-extra` before using them with success elsewhere.

### CODE REVIEW

**Comment by christiaanb** [comment]
Hi! Sorry for the lack of response on this. I recently became a father, so I've been somewhat "distracted" lately :-) I hope to have a proper look at this before the end of the year.

**Comment by philderbeast** [comment]
Congrats Christiaan.

**Comment by philderbeast** [comment]
I've modified my site's hakyll setup so that I can have unlisted review blog posts and moved the one about conditional coding there.

**Comment by christiaanb** [comment]
I think I'd like to drop the `cabal` workflow, since the `cabal`-based flow is already tested by the `haskell-ci` workflow, where the `haskell-ci` workflow is slightly more advanced.

**Comment by christiaanb** [comment]
@philderbeast Could you rebase on top of `master`? You can basically always pick your changes over what's in HEAD of master.

**Comment by philderbeast** [comment]
I put off doing the rebase until today as I was half awake yesterday from too much nordic ski and through sleepy eyes rewriting history felt too daunting.

**Pull request merged**
